pop-os/launcher

README.md

Noticed that my scripts stopped working with a pop-os launcher today. I had to move the scripts to a new location.
Update the readme with the correct folders (according to https://github.com/pop-os/launcher/blob/master/plugins/src/scripts/mod.rs#L17)
Also added an example script (not sure if we can pass parameters, but adding one with parameters would be useful as well)

Update references to scripts and plugins directories in readme

---

service/src/lib.rs

fix(service): Stale search results after interrupt

---

plugins/src/calc/plugin.ron

You might want it to say something different though, but at least not Math.JS any longer :)

fix(calc): Update description from JS to Rust dependency

---

Cargo.lock
README.md
plugins/Cargo.toml
plugins/src/calc/plugin.ron
plugins/src/desktop_entries/mod.rs
plugins/src/files/plugin.ron
plugins/src/find/plugin.ron
plugins/src/recent/plugin.ron
plugins/src/terminal/plugin.ron
plugins/src/web/plugin.ron

Closes #19 
Closes #20 
Closes #23 
Closes #25

Launcher Improvements

---

plugins/src/web/config.ron
plugins/src/web/plugin.ron

People don't like that `a` features Amazon and `b` features Bing. I'm
sure the same could be said for `g` for Google. Single-character aliases
seem to be a bad idea. Other aliases could also use some improvements
to add additional obvious aliases.
https://www.reddit.com/r/pop_os/comments/r19195/pop_os_how_do_i_stop_the_shell_from_showing/

chore(plugins-web): Change aliases to address complaints

---

Cargo.lock
plugins/Cargo.toml
plugins/src/desktop_entries/mod.rs

The Nix system path takes priority over the system path, but below Flatpak and Snap system paths, and the local nix path takes priority over all system paths, but below local Flatpak/Snap/.local paths.
To install nix in a multi-user capacity (system-wide):
```
sh <(curl -L https://nixos.org/nix/install) --daemon
```
Then you can install an application per-user and see it installed at `~/.nix-profile/share/applications`.
```
nix-env -i firefox
```
To install system-wide, switch to root and do the same and you'll find it installed in `/nix/var/nix/profiles/default/share/applications`
```
sudo su
bash
nix-env -i firefox
```

feat(desktop-entries): Nix application paths support

---

plugins/src/pop_shell/mod.rs

This addresses [an issue opened in the pop-os/shell repo](https://github.com/pop-os/shell/issues/1278) (is there a more convenient way to link to issues of a different project...?), where the ability to close an item in the launcher window via `Ctrl`+`Q` was lost, presumably after replacing the JS service with the Rust service.
The request handler for the *Quit* event of the *pop_shell* plugin just did nothing, instead of calling the `WindowQuit` function via D-Bus.
I am assuming this is just an oversight and there are no technical limitations preventing this (it seemed to work just fine when I tested it locally), hence this pull request :-)

fix(pop_shell): Implement 'Quit' request handler

---

plugins/src/calc/mod.rs

This changes the calculator behavior to stop showing "approx." in front of numbers when it has more decimal places than can be shown, by enabling qalc's Unicode support. It also explicitly sets the decimal mark to decimal points when that's preferred over commas.
For issue #71

Remove "approx." keyword and improve decimal point/comma handling

---

justfile

The previous `rm` invocation couldn't remove the directories and would throw an error.

fix(justfile): Fix uninstall of `launcher_dir`

---

plugins/src/desktop_entries/mod.rs

Currently the destkop-entry plugin retains the entries emitted by the freedesktop-desktop-entry crate in reverse order. 
For instance '$HOME/.local/share/applications/jetbrains-clion.desktop' is emitted first then 
overriden by '/usr/share/applications/jetbrains-clion.desktop'.  
Instead of `Hashset::replace`, `Hashset::insert` must be use to avoid overriding entries with higher priority. 
From freedesktop basedir specification: 
- " There is a set of preference ordered base directories relative to which data files should be searched. This set of directories is defined by the environment variable $XDG_DATA_DIRS." (see: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
From desktop-entries specification: 
-  "If multiple files have the same desktop file ID, the …

fix(plugin): load desktop entries from user dir

---

Cargo.lock
Cargo.toml
bin/Cargo.toml
bin/src/main.rs
plugins/src/web/config.rs
plugins/src/web/mod.rs
service/src/lib.rs
service/src/plugins/config.rs
service/src/plugins/mod.rs
src/lib.rs
toolkit/Cargo.toml
toolkit/src/lib.rs

This PR add the crate pop-launcher-toolkit which mostly reexport types needed to write a pop-launcher client and allow to 
add global features.  
Using only the pop-launcher bring just the minimal set of features required to build a client. 
Unfortunately this is not enough to implement some features. Cosmic-launcher make use of both the pop-launcher and the pop-launcher-service crates, onagre use them all. 
Since most client and plugin implementations will use more than the pop-launcher crate we might as well expose everything in a wrapper crate. It make things much easier for the developer and documentation is available in one place. 
1. Most of the configs related struct  and utility functions are now public 
I am using this in onagre to get the plugin regex and highlight the search …

feat: add a toolkit crate for both client and pop-launcher-bin

---

Cargo.lock
toolkit/Cargo.toml
toolkit/examples/man-pages-plugin.rs
toolkit/examples/plugin.ron
toolkit/src/lib.rs
toolkit/src/plugin_trait.rs

This PR add a `plugin_trait` feature which provides a helper trait to write plugins. 
It reduces the boiler plate needed by wrapping the stdin message passing in a default `run` function, and the stdout messages in `respond_with`. 
Additionally it implement the same logging behavior the default plugins have. 
For a concrete example you can take a look at [pop-launcher-mpd](https://github.com/oknozor/pop-launcher-mpd/blob/main/src/main.rs)

feat: add 'plugin_trait' feature to pop-launcher-toolkit

---

plugins/src/web/config.rs

While the configs come in, in the correct order (User, System, Distro), inside of the web plugin, keywords are overwritten by later keywords. This prevents the overwriting of already present keywords.
Follows clippy lint convention: https://rust-lang.github.io/rust-clippy/master/#map_entry
Fixes #125

fix(web): Prevent overwriting of keywords

---

plugins/src/web/config.rs
plugins/src/web/mod.rs

Some favicons are only provided with a resolution of 16x16, resulting in the logo being rather muddy inside of pop-launcher.
WIth this pull-request some changes were made.
- The Definition-Struct was extended with the icon-variable, which does not need to be defined.
- If it is defined, it is prioritized as a candidate for the downloaded icon.
- The cascading fallback icon download match-cases were replaced with a List of icon sources.
- The first successful icon of this list is used. 
As an example Nix Packages can be used
```
(
matches: ["np"],
queries: [(name: "Nix Packages", query: "search.nixos.org/packages?channel=unstable&query=")]
),
```
With this a rather muddy looking icon is used.
But should we use this instead:
```
(
matches: ["np"],
queries: [(
name: "Nix Packages", 
query: …
```

feat(web): specify icon

---

plugins/src/web/config.ron

I was missing starpage in pop launcher so I added it into 'launcher/plugins/src/web/config.ron' with either prompt 'sp' or 'startpage'.

add startpage to config.ron

---

scripts/session/session-shutdown.sh
scripts/session/session-suspend.sh

`poweroff` is the command used in the terminal, and `sleep` will be what Windows users will likely be used to. Apologies if this PR is unnecessary.

Add poweroff keyword to session-shutdown.sh and sleep keyword to session-suspend.sh

---

plugins/src/web/config.ron

I would like to search google scholar through the pop os launcher. The matches are subject to discussion, I typically use `scholar`, but DuckDuckGo uses the `!gsc` shortcut, so I added that as well.

Add Google Scholar to the search engines.

---

plugins/src/lib.rs
plugins/src/web/mod.rs

Prevents prefixing `https://` to custom URI schemes
Fixes #154

fix: allow web plugin to xdg-open custom URI schemes #154

---

plugins/src/find/mod.rs

Allows the user to find files within directories. Useful when files with the same name are found in many directories, e.g. `package.json`:
```
find MyProject/package.json
```
Fixes #150

feat(find): let fdfind use --full-path search to include directories

---

plugins/src/pop_shell/config.rs
plugins/src/pop_shell/mod.rs

This adds an optional `config.ron` file to the `pop_shell` plugin and allows users to configure what desktop window attributes they want searched (e.g. window title and/or window description).
For example, I prefer the window name not to be searched, because it's often a web page that has set the title of the window (e.g. in Chromium). Because window items in the launcher list always sort above desktop apps, these active window HTML pages can get in the way of fast/memory muscle launcher usage.
My config is as follows (`~/.local/share/pop-launcher/plugins/pop_shell/config.ron`):
```ron
(
search: (name: false, description: true),
)
```
With the above config, even if I'm on a google search page for `xournal++`, typing `xou` into pop-launcher will always load my desktop app, "Xournal++", …

feat(pop_shell): add config with window name/description search scope

---

scripts/session/session-lock.sh

This change is based on comments from the original PR #166.
https://github.com/pop-os/launcher/commit/970e71e2beec1a381e879e5df6652b47f6a017e0#commitcomment-98615497
https://github.com/pop-os/launcher/commit/970e71e2beec1a381e879e5df6652b47f6a017e0#commitcomment-98616065
In my initial testing with using `xdg-screensaver` I saw it fail a few times on the `lemp11`. This my have been a one off, but should be tested for.

use xdg-screensaver in session-lock script for cross compatibility

---

.vscode/settings.json
README.md
debian/control
debian/rules
debian/source/options
justfile
plugins/src/cosmic_toplevel/mod.rs

This change will ensure that the cosmic plugin is deactivated if the launcher is not in a COSMIC session. It checks if `XDG_CURRENT_DESKTOP` contains `COSMIC` to do so.
Fixes #169

fix: deactivate cosmic plugin when not in a COSMIC session

---

scripts/session/session-bios.sh

This is copied from the session-reboot.sh script but changed to reboot into BIOS, this can be handy for quickly making changes and not needing to use the BIOS key during boot.

Add session script for rebooting into BIOS

---

plugins/src/cosmic_toplevel/mod.rs
plugins/src/desktop_entries/mod.rs

The first commit changes the `cosmic-toplevel` plugin to always parse the desktop entries and match by the parsed `app_id` (which can be different than the file name) and parsed `StartupWMClass`.
The latter fixes icons not showing up primarily for Xwayland apps, who use the wm-class for identification, but don't always use the app-id in place. Additionally this fixes a lot of electron apps, that don't handle the app-id correctly in general up until the very latest release.
The second commit introduces the same fallback icon we are using in the `cosmic-toplevel` and `pop-shell` plugins for apps lacking an icon to the `desktop-entries` plugin as well. In case this in controversial, as this icon might now show up in places, where previously no icon was shown, this commit can easily be …

cosmic-toplevel: Also match by StartupWMClass

---

plugins/src/desktop_entries/mod.rs

Doesn't quite fix the broken context menu on gnome (that must be caused by the pop-shell extension), but required for cosmic-launcher to behave correctly...
(Sorry this took quite a few functions to fall into place to properly test this.. now it's definitely working on cosmic.)

desktop_entries: Fix activate context

---

plugins/src/cosmic_toplevel/mod.rs
plugins/src/cosmic_toplevel/plugin.ron

This should help fix https://github.com/pop-os/cosmic-launcher/issues/121. While, I believe they do currently show up with a specific enough search, cosmic_toplevel matches are listed at the top of the list when it is set to high priority.

Toplevel high priority

---

.vscode/settings.json
Cargo.lock
justfile
plugins/Cargo.toml
plugins/src/cosmic_toplevel/mod.rs
plugins/src/desktop_entries/mod.rs
plugins/src/desktop_entries/utils.rs
plugins/src/pop_shell/mod.rs
plugins/src/terminal/mod.rs

This depend on https://github.com/pop-os/freedesktop-desktop-entry/pull/15.
This will have the benefit of
- one api to get all desktop files
- cache them in your struct without a wrapper
- one api to search desktop files
- localisation support for searching entries
Currently, this works really great. The searching function still need refinement, like decide what fields to include in the search, give some field more weight, ect. But any improvement will benefit all cosmic component now.
Also, idk it it's possible yet, but it will be nice to give the returned response a score so that good matches get displayed first. I think this should be managed in the frontend since there can be multiple plugin at once, but i'm not sure.

use free_desktop_entry to search desktop file

---

justfile

This resolves an issue with Serpent OS when the installed plugin links point back to `/mason/install/usr/bin/pop-launcher`
Note, the AUR git pkg also uses a bit of a hack to rectify this, so lets just make it the default behaviour.
Serpent recipe change: https://github.com/serpent-os/recipes/commit/a607b85794069e2912a4a7684223fff6422f8119
Build log: https://dash.serpentos.com/logs/892/build.log

justfile: Use relative links for DESTDIR style installs

---

README.md

The JSON equivalent types did not match the Rust types in the
documentation. Fix the JSON equivalents to match the Rust type, which is
what the program actually sends.

readme: fix Response JSON equivalent types

---

plugins/src/desktop_entries/mod.rs

specific example: vscode from flathub
**changes tl;dr**
- the `desktop_entries` plugin adds each appid to a dedupe check really early in the filter function
- some programs may include multiple `.desktop` files, for instance vscode including a `com.visualstudio.code.desktop` and `com.visualstudio.code-url-handler.desktop`
- if one entry otherwise fails the filter (eg: `de.no_display()` set for a URL handler) then any other entries with the same appid get ignored
- this changes that behaviour so we only ignore the appid when we've added it to our list of entries

Allow desktop entries with shell URL handlers to correctly display in launcher

---

plugins/src/cosmic_toplevel/mod.rs

example:
- install `OBS` (open broadcasting software) via `cosmic-store`
-  the `.desktop` file has a `StartupWMClass=obs`, which causes this issue
- open `cosmic-files` and create a folder called `obs`
- search for `obs`
- observe that the `cosmic-files` entry has the incorrect description/icon (but _does_ open the right window)
searching manually does indeed confirm that the wrong description / icon are being passed in:
```
{"Search":"obs"}
[ .. ]
{"Append":{"id":14,"name":"Flatpak - Free and Open Source Streaming/Recording Software","description":"obs — COSMIC Files","keywords":null,"icon":{"Name":"com.obsproject.Studio"},"exec":null,"window":[0,14]}}
```
with this fix:
```
{"Search":"obs"}
[ .. ]
{"Append":{"id":14,"name":"System","description":"obs — COSMIC …
```

Updating cosmic_toplevel to correctly match desktop entries in some ambiguous cases

---

Cargo.lock
Cargo.toml
plugins/Cargo.toml
plugins/src/cosmic_toplevel/mod.rs
plugins/src/desktop_entries/mod.rs
plugins/src/desktop_entries/utils.rs
plugins/src/pop_shell/mod.rs
plugins/src/terminal/mod.rs

Updates the freedesktop-desktop-entry crate, which should fix some applications not appearing in the search, or not having the correct icon. However, it does alter queries so there may be some differences in search results.

fix: update freedesktop-desktop-entry
