- plugins/src/pop_shell/mod.rs
- src/lib.rs
Requires https://github.com/pop-os/shell/pull/1246
> feat(plugin-pop-shell): Get window icon from desktop entry

- plugins/src/terminal/mod.rs
This will prevent a lingering process when executing `:command` in the launcher
> fix(terminal): Do not invoke read command on shell execution

- README.md
- plugins/src/calc/plugin.ron
- plugins/src/desktop_entries/plugin.ron
- plugins/src/files/plugin.ron
- plugins/src/find/plugin.ron
- plugins/src/terminal/plugin.ron
- plugins/src/web/plugin.ron
- service/src/plugins/config.rs
- service/src/plugins/help.rs
> feat: add a history attribute to plugin config as described in #110

- plugins/src/web/config.ron
This PR does the following:
- Add UPS tracking number search
> add UPS search query

- plugins/src/calc/plugin.ron
This addition fixes https://github.com/pop-os/launcher/issues/126
> addition to regex

- plugins/src/web/config.ron
This PR does the following:
- Adds Fedex tracking to launcher
> Add Fedex tracking

- plugins/src/web/config.ron
Added Ecosia Search as an option in the launcher
> Add Ecosia Search to config.ron

- scripts/session/session-logout.sh
- scripts/session/session-reboot.sh
- scripts/session/session-shutdown.sh
- scripts/session/session-suspend.sh
- added fallbacks in session scripts for systems that do not have GNOME but do have systemd
> fix: systemd fallbacks for session scripts

- plugins/src/web/config.ron
- plugins/src/web/mod.rs
Opens a website in default browser, e.g. `www github.com`
> Add generic `www` pattern to open any website

- plugins/src/scripts/mod.rs
This PR allows the shebang line in a script file to have more flexibility:
1. Whitespace is accepted after the `#!` characters, so `#! /bin/bash` is now ok.
2. Any args passed to the command in the shebang are honored, so `#!/usr/bin/env nu` will work (for example)
Fixes #142 (except for stderr and non-`#` metadata comment lines)
> Handle shebang more thoroughly in scripts plugin

- Cargo.lock
- bin/src/main.rs
- debian/control
- debian/pop-launcher.links
- justfile
- plugins/Cargo.toml
- plugins/src/cosmic_toplevel/mod.rs
- plugins/src/cosmic_toplevel/plugin.ron
- plugins/src/cosmic_toplevel/toplevel_handler.rs
- plugins/src/lib.rs
- plugins/src/web/mod.rs
- service/src/client.rs
- src/lib.rs
the cosmic toplevel plugin adds support for cosmic windows as items in the launcher.
> Cosmic toplevel plugin

- README.md
- plugins/src/lib.rs
- scripts/system76-power/graphics-compute.sh
- scripts/system76-power/graphics-discrete.sh
- scripts/system76-power/graphics-hybrid.sh
- scripts/system76-power/graphics-integrated.sh
Fixes various minor typos in documentation and scripts.
> fix: typos

- README.md
add info on standard logger to readme
> [ADD] add information on standard logging

- plugins/src/terminal/mod.rs
fixes https://github.com/pop-os/cosmic-launcher/issues/82
> feat: prefer cosmic-term in terminal plugin

- plugins/src/web/config.ron
Just add an option to search the web using the Kagi search engine at https://kagi.com/
> Add support for Kagi Search

- plugins/src/cosmic_toplevel/mod.rs
Raising the required match score fixes #228 based on my testing and matching individual words seems to better match window titles.
> fix(toplevel): require higher toplevel match score

- scripts/session/session-bios.sh
- scripts/session/session-lock.sh
- scripts/session/session-logout.sh
- scripts/session/session-reboot.sh
- scripts/session/session-shutdown.sh
- scripts/session/session-suspend.sh
- scripts/system76-power/graphics-compute.sh
- scripts/system76-power/graphics-discrete.sh
- scripts/system76-power/graphics-hybrid.sh
- scripts/system76-power/graphics-integrated.sh
> Use more generic shell script shebang

- plugins/src/desktop_entries/mod.rs
Closes: pop-os/cosmic-epoch#905
User defined desktop entries should override the system's applications. The old logic continued to parse apps which overrode user preference, such as with the `NoDisplay` key.
* ~~Removed old `NoDisplay` code~~
* Revert the above
* Small clean up
> fix(desktop_entries): Respect `NoDisplay` override precedence

- service/src/lib.rs
- service/src/priority.rs
- service/src/recent.rs
this should fix https://github.com/pop-os/cosmic-launcher/issues/191
The weights could be adjusted for recent or frequency score if necessary.
> fix: total ordering for Priority

- scripts/session/session-logout.sh
- scripts/session/session-reboot.sh
- scripts/session/session-shutdown.sh
This should display a popup dialog with a timer for logout, reboot, and shutdown.
> refactor: invoke cosmic-osd in session scripts when available

- service/src/lib.rs
This should fix https://github.com/pop-os/cosmic-launcher/issues/303. We could tweak the values to be smaller if this seems to affect anything else in a negative way.
> fix: introduce decay factor for keyword weight based on index, and shrink the description match weight.
